INSERT INTO osc.tb_projeto (
	id_projeto, 
	id_osc, 
	tx_nome_projeto, 
	ft_nome_projeto, 
	cd_status_projeto, 
	ft_status_projeto, 
	dt_data_inicio_projeto, 
	ft_data_inicio_projeto, 
	dt_data_fim_projeto, 
	ft_data_fim_projeto, 
	tx_link_projeto, 
	ft_link_projeto, 
	nr_total_beneficiarios, 
	ft_total_beneficiarios, 
	nr_valor_captado_projeto, 
	ft_valor_captado_projeto, 
	nr_valor_total_projeto, 
	ft_valor_total_projeto, 
	cd_abrangencia_projeto, 
	ft_abrangencia_projeto, 
	cd_zona_atuacao_projeto, 
	ft_zona_atuacao_projeto, 
	tx_descricao_projeto, 
	ft_descricao_projeto, 
	ft_metodologia_monitoramento, 
	tx_metodologia_monitoramento, 
	tx_identificador_projeto_externo, 
	ft_identificador_projeto_externo, 
	bo_oficial
)
VALUES (
	1, 
	987654, 
	'Projeto Teste 1', 
	'MPOG/SICONV', 
	1, 
	'MPOG/SICONV', 
	'2017-01-01', 
	'MPOG/SICONV', 
	'2018-01-01', 
	'MPOG/SICONV', 
	null, 
	null, 
	null, 
	null, 
	null, 
	null, 
	100000.00, 
	'MPOG/SICONV', 
	null, 
	null, 
	null, 
	null, 
	'Até quando, Catilina, abusarás da nossa paciência? Por quanto tempo a tua loucura há de zombar de nós? A que extremos se há de precipitar a tua desenfreada audácia? Nem a guarda do Palatino, nem a ronda noturna da cidade, nem o temor do povo, nem a afluência de todos os homens de bem, nem este local tão bem protegido para a reunião do Senado, nem a expressão do voto destas pessoas, nada disto conseguiu perturbar-te? Não te dás conta que os teus planos foram descobertos? Não vês que a tua conspiração a têm já dominada todos estes que a conhecem? Quem, dentre nós, pensas tu que ignora o que fizeste na noite passada e na precedente, onde estiveste, com quem te encontraste, que decisão tomaste? Oh tempos, oh costumes!', 
	'MPOG/SICONV', 
	null, 
	null, 
	123456, 
	'MPOG/SICONV', 
	true
);



INSERT INTO osc.tb_projeto (
	id_projeto, 
	id_osc, 
	tx_nome_projeto, 
	ft_nome_projeto, 
	cd_status_projeto, 
	ft_status_projeto, 
	dt_data_inicio_projeto, 
	ft_data_inicio_projeto, 
	dt_data_fim_projeto, 
	ft_data_fim_projeto, 
	tx_link_projeto, 
	ft_link_projeto, 
	nr_total_beneficiarios, 
	ft_total_beneficiarios, 
	nr_valor_captado_projeto, 
	ft_valor_captado_projeto, 
	nr_valor_total_projeto, 
	ft_valor_total_projeto, 
	cd_abrangencia_projeto, 
	ft_abrangencia_projeto, 
	cd_zona_atuacao_projeto, 
	ft_zona_atuacao_projeto, 
	tx_descricao_projeto, 
	ft_descricao_projeto, 
	ft_metodologia_monitoramento, 
	tx_metodologia_monitoramento, 
	tx_identificador_projeto_externo, 
	ft_identificador_projeto_externo, 
	bo_oficial
)
VALUES (
	2, 
	987654, 
	'Projeto Teste 2', 
	'Representante', 
	1, 
	'Representante', 
	'2016-01-01', 
	'Representante', 
	'2020-01-01', 
	'Representante', 
	'www.projeto2.com.br', 
	'Representante', 
	1500, 
	'Representante', 
	252134.49, 
	'Representante', 
	285000.00, 
	'Representante', 
	1, 
	'Representante', 
	1, 
	'Representante', 
	'Até quando, Catilina, abusarás da nossa paciência? Por quanto tempo a tua loucura há de zombar de nós? A que extremos se há de precipitar a tua desenfreada audácia? Nem a guarda do Palatino, nem a ronda noturna da cidade, nem o temor do povo, nem a afluência de todos os homens de bem, nem este local tão bem protegido para a reunião do Senado, nem a expressão do voto destas pessoas, nada disto conseguiu perturbar-te? Não te dás conta que os teus planos foram descobertos? Não vês que a tua conspiração a têm já dominada todos estes que a conhecem? Quem, dentre nós, pensas tu que ignora o que fizeste na noite passada e na precedente, onde estiveste, com quem te encontraste, que decisão tomaste? Oh tempos, oh costumes!', 
	'Representante', 
	'Consultoria externa', 
	'Representante', 
	null, 
	null, 
	true
);



INSERT INTO osc.tb_projeto (
	id_projeto, 
	id_osc, 
	tx_nome_projeto, 
	ft_nome_projeto, 
	cd_status_projeto, 
	ft_status_projeto, 
	dt_data_inicio_projeto, 
	ft_data_inicio_projeto, 
	dt_data_fim_projeto, 
	ft_data_fim_projeto, 
	tx_link_projeto, 
	ft_link_projeto, 
	nr_total_beneficiarios, 
	ft_total_beneficiarios, 
	nr_valor_captado_projeto, 
	ft_valor_captado_projeto, 
	nr_valor_total_projeto, 
	ft_valor_total_projeto, 
	cd_abrangencia_projeto, 
	ft_abrangencia_projeto, 
	cd_zona_atuacao_projeto, 
	ft_zona_atuacao_projeto, 
	tx_descricao_projeto, 
	ft_descricao_projeto, 
	ft_metodologia_monitoramento, 
	tx_metodologia_monitoramento, 
	tx_identificador_projeto_externo, 
	ft_identificador_projeto_externo, 
	bo_oficial
)
VALUES (
	3, 
	987654, 
	'Projeto Teste 3', 
	'Representante', 
	1, 
	'Representante', 
	'2017-01-01', 
	'Representante', 
	'2017-07-01', 
	'Representante', 
	'www.projeto3.com.br', 
	'Representante', 
	500, 
	'Representante', 
	4987.25, 
	'Representante', 
	5000.00, 
	'Representante', 
	1, 
	'Representante', 
	1, 
	'Representante', 
	'Até quando, Catilina, abusarás da nossa paciência? Por quanto tempo a tua loucura há de zombar de nós? A que extremos se há de precipitar a tua desenfreada audácia? Nem a guarda do Palatino, nem a ronda noturna da cidade, nem o temor do povo, nem a afluência de todos os homens de bem, nem este local tão bem protegido para a reunião do Senado, nem a expressão do voto destas pessoas, nada disto conseguiu perturbar-te? Não te dás conta que os teus planos foram descobertos? Não vês que a tua conspiração a têm já dominada todos estes que a conhecem? Quem, dentre nós, pensas tu que ignora o que fizeste na noite passada e na precedente, onde estiveste, com quem te encontraste, que decisão tomaste? Oh tempos, oh costumes!', 
	'Representante', 
	'Consultoria externa', 
	'Representante', 
	null, 
	null, 
	true
);
