INSERT INTO osc.tb_localizacao (
	id_osc, 
	tx_endereco, 
	ft_endereco, 
	nr_localizacao, 
	ft_localizacao, 
	tx_endereco_complemento, 
	ft_endereco_complemento, 
	tx_bairro, 
	ft_bairro, 
	cd_municipio, 
	ft_municipio, 
	geo_localizacao, 
	ft_geo_localizacao, 
	nr_cep, 
	ft_cep, 
	tx_endereco_corrigido, 
	ft_endereco_corrigido, 
	tx_bairro_encontrado, 
	ft_bairro_encontrado, 
	cd_fonte_geocodificacao, 
	ft_fonte_geocodificacao, 
	dt_geocodificacao, 
	ft_data_geocodificacao, 
	bo_oficial
)
VALUES (
	987654, 
	'RUA CAPITAO SILVIO GONCALVES DE FARIAS', 
	'MTE/RAIS', 
	981, 
	'MTE/RAIS', 
	'Lote 2', 
	'Representante', 
	'BOSQUE', 
	'MTE/RAIS', 
	1100155, 
	'MTE/RAIS', 
	'010100002042120000FC40498B37214FC0EED075A4A47525C0', 
	'Galileo', 
	76920000, 
	'MTE/RAIS', 
	'Rua Capitão Silvio Gonçalves de Farias', 
	'Representante', 
	'Jardim Bandeirantes', 
	'Representante', 
	3, 
	'Administrador', 
	'2017-02-06', 
	'Administrador', 
	true
);