INSERT INTO osc.tb_contato (
	id_osc, 
	tx_telefone, 
	ft_telefone, 
	tx_email, 
	ft_email, 
	nm_representante, 
	ft_representante, 
	tx_site, 
	ft_site, 
	tx_facebook, 
	ft_facebook, 
	tx_google, 
	ft_google, 
	tx_linkedin, 
	ft_linkedin, 
	tx_twitter, 
	ft_twitter
)
VALUES (
	987654, 
	'1234-5678', 
	'MTE/RAIS', 
	'mapaosc@ipea.gov.br',
	'MTE/RAIS', 
	'João Américo Abelardo', 
	'Representante', 
	'orgteste.com',
	'Representante', 
	'www.facebook.com/orgteste', 
	'Representante', 
	'www.google.com/orgteste', 
	'Representante', 
	'www.linkedin.com/orgteste', 
	'Representante', 
	'www.twitter.com/orgteste', 
	'Representante'
);
