DROP MATERIALIZED VIEW portal.vw_osc_participacao_social_conselho;
ALTER TABLE syst.dc_conselho ALTER COLUMN tx_nome_conselho TYPE text;
SELECT setval('syst.dc_conselho_cd_conselho_seq', max(cd_conselho))
FROM syst.dc_conselho;
INSERT INTO syst.dc_conselho(tx_nome_conselho)
VALUES
('Conselho Municipal de Defesa do Meio Ambiente'),
('Conselho Municipal de Educação'),
('Conselho Municipal de Prevenção, Repressão e Fiscalização de Entorpecentes'),
('Conselho Consultivo Municipal do Patrimônio Histórico, Arqueológico, Arquitetônico e Paisagístico'),
('Conselho Municipal de Desporto'),
('Conselho Municipal dos Direitos da Criança e do Adolescente'),
('Conselho Municipal para Assuntos da Pessoa com Deficiência (CMAPD)/Conselho Municipal dos Direitos da Pessoa com Deficiência'),
('Conselho Municipal de Juventude'),
('Conselho Municipal de Cultura'),
('Conselho Municipal de Acompanhamento e Controle Social do Fundeb'),
('Conselho Municipal de Assistência Social'),
('Conselho Municipal do Orçamento Participativo'),
('Conselho Municipal de Turismo'),
('Conselho Municipal de Alimentação Escolar'),
('Conselho Municipal de Segurança Alimentar e Nutricional “Fome Zero”'),
('Conselho Municipal de Transporte e Trânsito'),
('Conselho Municipal do Idoso/Conselho Municipal dos Direitos da Pessoa Idosa'),
('Conselho Municipal de Saúde'),
('Conselho Municipal de Habitação'),
('Conselho de Controle Social do Programa Bolsa Família'),
('Conselho Municipal de Recursos Hídricos'),
('Conselho Municipal Antidrogas/Conselho Municipal de Políticas sobre Drogas'),
('Conselho Municipal de Participação da Comunidade Nordestina'),
('Conselho Municipal de Desenvolvimento Urbano'),
('Conselho Municipal de Proteção aos Animais'),
('Conselho Municipal de Proteção e Defesa do Consumidor'),
('Conselho Municipal de Desenvolvimento Econômico'),
('Conselho Municipal de Geração de Trabalho e Renda'),
('Conselho Municipal de Inclusão Digital'),
('Conselho Municipal de Promoção da Igualdade Racial'),
('Conselho Municipal do Patrimônio Histórico, Artístico, Ambiental e Cultural'),
('Conselho Municipal de Esporte, Recreação e Lazer'),
('Conselho Municipal de Políticas para Mulheres'),
('Conselho Municipal de Segurança Alimentar e Nutricional'),
('Conselho Estadual de Defesa do Meio Ambiente'),
('Conselho Estadual de Educação'),
('Conselho Estadual de Prevenção, Repressão e Fiscalização de Entorpecentes'),
('Conselho Consultivo Estadual do Patrimônio Histórico, Arqueológico, Arquitetônico e Paisagístico'),
('Conselho Estadual de Desporto'),
('Conselho Estadual dos Direitos da Criança e do Adolescente'),
('Conselho Estadual para Assuntos da Pessoa com Deficiência (CMAPD)/Conselho Municipal dos Direitos da Pessoa com Deficiência'),
('Conselho Estadual de Juventude'),
('Conselho Estadual de Cultura'),
('Conselho Estadual de Acompanhamento e Controle Social do Fundeb'),
('Conselho Estadual de Assistência Social'),
('Conselho Estadual do Orçamento Participativo'),
('Conselho Estadual de Turismo'),
('Conselho Estadual de Alimentação Escolar'),
('Conselho Estadual de Segurança Alimentar e Nutricional “Fome Zero”'),
('Conselho Estadual de Transporte e Trânsito'),
('Conselho Estadual do Idoso/Conselho Municipal dos Direitos da Pessoa Idosa'),
('Conselho Estadual de Saúde'),
('Conselho Estadual de Habitação'),
('Conselho Estadual de Recursos Hídricos'),
('Conselho Estadual Antidrogas/Conselho Municipal de Políticas sobre Drogas'),
('Conselho Estadual de Participação da Comunidade Nordestina'),
('Conselho Estadual de Desenvolvimento Urbano'),
('Conselho Estadual de Proteção aos Animais'),
('Conselho Estadual de Proteção e Defesa do Consumidor'),
('Conselho Estadual de Desenvolvimento Econômico'),
('Conselho Estadual de Geração de Trabalho e Renda'),
('Conselho Estadual de Inclusão Digital'),
('Conselho Estadual de Promoção da Igualdade Racial'),
('Conselho Estadual do Patrimônio Histórico, Artístico, Ambiental e Cultural'),
('Conselho Estadual de Esporte, Recreação e Lazer'),
('Conselho Estadual de Políticas para Mulheres'),
('Conselho Estadual de Segurança Alimentar e Nutricional'),
('Outro Conselho');
CREATE MATERIALIZED VIEW portal.vw_osc_participacao_social_conselho
AS 

SELECT
	tb_osc.id_osc,
	tb_osc.tx_apelido_osc,
	tb_participacao_social_conselho.id_conselho,
	tb_participacao_social_conselho.cd_conselho,
	(SELECT tx_nome_conselho FROM syst.dc_conselho WHERE cd_conselho = tb_participacao_social_conselho.cd_conselho) AS tx_nome_conselho,
	tb_participacao_social_conselho.ft_conselho,
	tb_participacao_social_conselho.cd_tipo_participacao,
	(SELECT tx_nome_tipo_participacao FROM syst.dc_tipo_participacao WHERE cd_tipo_participacao = tb_participacao_social_conselho.cd_tipo_participacao) AS tx_nome_tipo_participacao,
	tb_participacao_social_conselho.ft_tipo_participacao,
	tb_participacao_social_conselho.tx_periodicidade_reuniao,
	tb_participacao_social_conselho.ft_periodicidade_reuniao,
	TO_CHAR(tb_participacao_social_conselho.dt_data_inicio_conselho, 'DD-MM-YYYY') AS dt_data_inicio_conselho,
	tb_participacao_social_conselho.ft_data_inicio_conselho,
	TO_CHAR(tb_participacao_social_conselho.dt_data_fim_conselho, 'DD-MM-YYYY') AS dt_data_fim_conselho,
	tb_participacao_social_conselho.ft_data_fim_conselho
FROM osc.tb_osc
INNER JOIN osc.tb_participacao_social_conselho ON tb_osc.id_osc = tb_participacao_social_conselho.id_osc
WHERE tb_osc.bo_osc_ativa;
-- ddl-end --
ALTER MATERIALIZED VIEW portal.vw_osc_participacao_social_conselho OWNER TO postgres;
-- ddl-end --