INSERT INTO syst.dc_conferencia(tx_nome_conferencia)
VALUES
('Conferência Estadual de Aprendizagem Profissional'),
('Conferência Estadual de Aqüicultura e Pesca'),
('Conferência Estadual de Assistência Social'),
('Conferência Estadual de Assistência Técnica e Extensão Rural'),
('Conferência Estadual de Cidades'),
('Conferência Estadual de Ciência, Tecnologia e Inovação'),
('Conferência Estadual de Comunicação'),
('Conferência Estadual de Cultura'),
('Conferência Estadual de Proteção e Defesa Civil'),
('Conferência Estadual de Desenvolvimento Regional'),
('Conferência Estadual de Desenvolvimento Rural Sustentável e Solidário'),
('Conferência Estadual dos Direitos da Criança e do Adolescente'),
('Conferência Estadual de Direitos Humanos'),
('Conferência Estadual dos Direitos da Pessoa Idosa'),
('Conferência Estadual dos Direitos da Pessoa com Deficiência'),
('Conferência Estadual de Economia Solidária'),
('Conferência Estadual de Educação'),
('Conferência Estadual de Educação Básica'),
('Conferência Estadual de Educação Escolar Indígena'),
('Conferência Estadual de Educação Profissional e Tecnológica'),
('Conferência Estadual do Emprego e Trabalho Decente'),
('Conferência Estadual do Esporte'),
('Conferência Estadual Políticas Públicas de Direitos Humanos de Lésbicas, Gays, Bissexuais, Travestis e Transexuais'),
('Conferência Estadual de Recursos Humanos Para a Saúde'),
('Conferência Estadual de Gestão, Trabalho, Educação e Saúde'),
('Conferência Estadual da Juventude'),
('Conferência Estadual Infanto-Juvenil pelo Meio Ambiente'),
('Conferência Estadual de Medicamentos e Assistência Farmaceutica'),
('Conferência Estadual do Meio Ambiente'),
('Conferência Estadual sobre Migrações e Refúgio'),
('Conferência Estadual de Políticas para as Mulheres'),
('Conferência Estadual de Política Indigenista'),
('Conferência Estadual de Promoção da Igualdade Racial'),
('Conferência Estadual de Recursos Humanos da Administração Pública Federal'),
('Conferência Estadual de Saúde'),
('Conferência Estadual de Saúde Ambiental'),
('Conferência Estadual de Saúde Bucal'),
('Conferência Estadual de Saúde Indígena'),
('Conferência Estadual de Saúde Mental'),
('Conferência Estadual de Saúde do Trabalhador'),
('Conferência Estadual de Segurança Alimentar'),
('Conferência Estadual de Segurança Pública'),
('Conferência Estadual sobre Transparência e Controle Social'),
('Conferência Municipal de Aprendizagem Profissional'),
('Conferência Municipal de Aqüicultura e Pesca'),
('Conferência Municipal de Assistência Social'),
('Conferência Municipal de Assistência Técnica e Extensão Rural'),
('Conferência Municipal de Cidades'),
('Conferência Municipal de Ciência, Tecnologia e Inovação'),
('Conferência Municipal de Comunicação'),
('Conferência Municipal de Cultura'),
('Conferência Municipal de Proteção e Defesa Civil'),
('Conferência Municipal de Desenvolvimento Regional'),
('Conferência Municipal de Desenvolvimento Rural Sustentável e Solidário'),
('Conferência Municipal dos Direitos da Criança e do Adolescente'),
('Conferência Municipal de Direitos Humanos'),
('Conferência Municipal dos Direitos da Pessoa Idosa'),
('Conferência Municipal dos Direitos da Pessoa com Deficiência'),
('Conferência Municipal de Economia Solidária'),
('Conferência Municipal de Educação'),
('Conferência Municipal de Educação Básica'),
('Conferência Municipal de Educação Escolar Indígena'),
('Conferência Municipal de Educação Profissional e Tecnológica'),
('Conferência Municipal do Emprego e Trabalho Decente'),
('Conferência Municipal do Esporte'),
('Conferência Municipal Políticas Públicas de Direitos Humanos de Lésbicas, Gays, Bissexuais, Travestis e Transexuais'),
('Conferência Municipal de Recursos Humanos Para a Saúde'),
('Conferência Municipal de Gestão, Trabalho, Educação e Saúde'),
('Conferência Municipal da Juventude'),
('Conferência Municipal Infanto-Juvenil pelo Meio Ambiente'),
('Conferência Municipal de Medicamentos e Assistência Farmaceutica'),
('Conferência Municipal do Meio Ambiente'),
('Conferência Municipal sobre Migrações e Refúgio'),
('Conferência Municipal de Políticas para as Mulheres'),
('Conferência Municipal de Política Indigenista'),
('Conferência Municipal de Promoção da Igualdade Racial'),
('Conferência Municipal de Recursos Humanos da Administração Pública Federal'),
('Conferência Municipal de Saúde'),
('Conferência Municipal de Saúde Ambiental'),
('Conferência Municipal de Saúde Bucal'),
('Conferência Municipal de Saúde Indígena'),
('Conferência Municipal de Saúde Mental'),
('Conferência Municipal de Saúde do Trabalhador'),
('Conferência Municipal de Segurança Alimentar'),
('Conferência Municipal de Segurança Pública'),
('Conferência Municipal sobre Transparência e Controle Social'),
('Outra Conferência');