INSERT INTO syst.dc_conselho(tx_nome_conselho)
VALUES
('Conselho Estadual de Recursos Hídricos'),
('Conselho Estadual de Desenvolvimento Rural Sustentável'),
('Conselho Estadual de Aquicultura e Pesca'),
('Conselho Estadual de Ciência e Tecnologia'),
('Conselho Estadual de Política Cultural'),
('Conselho Estadual de Educação'),
('Conselho Estadual de Previdência Social'),
('Conselho Estadual de Proteção e Defesa Civil'),
('Comissão Estadual para Erradicação do Trabalho Escravo'),
('Conselho Estadual de Combate à Discriminação e Promoção dos Direitos de LGBT'),
('Conselho Estadual de Direitos Humanos'),
('Conselho Estadual de Política Criminal e Penitenciária'),
('Conselho Estadual de Política Indigenista'),
('Conselho Estadual de Políticas Sobre Drogas'),
('Conselho Estadual de Promoção da Igualdade Racial'),
('Conselho Estadual de Segurança Pública'),
('Conselho Estadual dos Direitos da Criança e do Adolescente'),
('Conselho Estadual dos Direitos da Mulher'),
('Conselho Estadual dos Direitos da Pessoa com Deficiência'),
('Conselho Estadual dos Direitos do Idoso'),
('Conselho Estadual de Saúde'),
('Conselho Estadual de Assistência Social'),
('Conselho Estadual dos Povos e Comunidades Tradicionais'),
('Conselho Estadual do Esporte'),
('Conselho Estadual do Meio Ambiente'),
('Comissão Estadual de Erradicação do Trabalho Infantil'),
('Conselho Estadual de Economia Solidária'),
('Conselho Estadual de Imigração'),
('Conselho Estadual de Turismo'),
('Conselho Estadual de Política Energética'),
('Conselho Estadual de Segurança Alimentar e Nutricional'),
('Conselho Estadual de Juventude'),
('Conselho Municipal de Recursos Hídricos'),
('Conselho Municipal de Desenvolvimento Rural Sustentável'),
('Conselho Municipal de Aquicultura e Pesca'),
('Conselho Municipal de Ciência e Tecnologia'),
('Conselho Municipal de Política Cultural'),
('Conselho Municipal de Educação'),
('Conselho Municipal de Previdência Social'),
('Conselho Municipal de Proteção e Defesa Civil'),
('Comissão Municipal para Erradicação do Trabalho Escravo'),
('Conselho Municipal de Combate à Discriminação e Promoção dos Direitos de LGBT'),
('Conselho Municipal de Direitos Humanos'),
('Conselho Municipal de Política Criminal e Penitenciária'),
('Conselho Municipal de Política Indigenista'),
('Conselho Municipal de Políticas Sobre Drogas'),
('Conselho Municipal de Promoção da Igualdade Racial'),
('Conselho Municipal de Segurança Pública'),
('Conselho Municipal dos Direitos da Criança e do Adolescente'),
('Conselho Municipal dos Direitos da Mulher'),
('Conselho Municipal dos Direitos da Pessoa com Deficiência'),
('Conselho Municipal dos Direitos do Idoso'),
('Conselho Municipal de Saúde'),
('Conselho Municipal de Assistência Social'),
('Conselho Municipal dos Povos e Comunidades Tradicionais'),
('Conselho Municipal do Esporte'),
('Conselho Municipal do Meio Ambiente'),
('Comissão Municipal de Erradicação do Trabalho Infantil'),
('Conselho Municipal de Economia Solidária'),
('Conselho Municipal de Imigração'),
('Conselho Municipal de Turismo'),
('Conselho Municipal de Política Energética'),
('Conselho Municipal de Segurança Alimentar e Nutricional'),
('Conselho Municipal de Juventude'),
('Outro Conselho');